// <auto-generated />
using System;
using AccesoriosArgentinos.Modelos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccesoriosArgentinos.Migrations
{
    [DbContext(typeof(AccesoriosDbContext))]
    partial class AccesoriosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Deposito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Depositos");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.EstadosProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosProduccion");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Inyectora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inyectoras");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.MaterialPieza", b =>
                {
                    b.Property<int>("PiezaId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Proporcion")
                        .HasColumnType("int");

                    b.HasKey("PiezaId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialPiezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Matriz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepositoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepositoId1")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepositoId1");

                    b.ToTable("Matrices");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Operario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operarios");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.OrdenesProduccionCabecera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InyectoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InyectoraId");

                    b.ToTable("OrdenesProduccionCabeceras");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.OrdenesProduccionDetalle", b =>
                {
                    b.Property<int>("PiezaId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenProduccionCabeceraId")
                        .HasColumnType("int");

                    b.Property<int>("Ajuste")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("ImpactosVacios")
                        .HasColumnType("int");

                    b.Property<int?>("MatrizId")
                        .HasColumnType("int");

                    b.Property<int?>("OperarioId")
                        .HasColumnType("int");

                    b.HasKey("PiezaId", "OrdenProduccionCabeceraId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MatrizId");

                    b.HasIndex("OperarioId");

                    b.HasIndex("OrdenProduccionCabeceraId");

                    b.ToTable("OrdenesProduccionDetalles");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Pieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Bocas")
                        .HasColumnType("int");

                    b.Property<string>("Calefaccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoFabricacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Curado")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InyectoraId")
                        .HasColumnType("int");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("MatrizId")
                        .HasColumnType("int");

                    b.Property<string>("NoyoA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<string>("PosicionApertura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresionInyeccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProduccionPorHora")
                        .HasColumnType("int");

                    b.Property<string>("TiempoDeInyeccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VelocidadInyeccion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InyectoraId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MatrizId");

                    b.ToTable("Piezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.MaterialPieza", b =>
                {
                    b.HasOne("AccesoriosArgentinos.Modelos.Material", "Material")
                        .WithMany("MaterialPiezas")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccesoriosArgentinos.Modelos.Pieza", "Pieza")
                        .WithMany("MaterialPiezas")
                        .HasForeignKey("PiezaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Pieza");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Matriz", b =>
                {
                    b.HasOne("AccesoriosArgentinos.Modelos.Deposito", "Deposito")
                        .WithMany("Matrices")
                        .HasForeignKey("DepositoId1");

                    b.Navigation("Deposito");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.OrdenesProduccionCabecera", b =>
                {
                    b.HasOne("AccesoriosArgentinos.Modelos.Inyectora", "Inyectora")
                        .WithMany("OrdenesProduccionCabeceras")
                        .HasForeignKey("InyectoraId");

                    b.Navigation("Inyectora");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.OrdenesProduccionDetalle", b =>
                {
                    b.HasOne("AccesoriosArgentinos.Modelos.EstadosProduccion", "Estado")
                        .WithMany("OrdenesProduccionDetalles")
                        .HasForeignKey("EstadoId");

                    b.HasOne("AccesoriosArgentinos.Modelos.Matriz", "Matriz")
                        .WithMany("OrdenesProduccionDetalles")
                        .HasForeignKey("MatrizId");

                    b.HasOne("AccesoriosArgentinos.Modelos.Operario", "Operario")
                        .WithMany("OrdenesProduccionDetalles")
                        .HasForeignKey("OperarioId");

                    b.HasOne("AccesoriosArgentinos.Modelos.OrdenesProduccionCabecera", "OrdenProduccionCabecera")
                        .WithMany("OrdenesProduccionDetalles")
                        .HasForeignKey("OrdenProduccionCabeceraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccesoriosArgentinos.Modelos.Pieza", "Pieza")
                        .WithMany("OrdenesProduccionDetalles")
                        .HasForeignKey("PiezaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Matriz");

                    b.Navigation("Operario");

                    b.Navigation("OrdenProduccionCabecera");

                    b.Navigation("Pieza");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Pieza", b =>
                {
                    b.HasOne("AccesoriosArgentinos.Modelos.Inyectora", "Inyectora")
                        .WithMany("Piezas")
                        .HasForeignKey("InyectoraId");

                    b.HasOne("AccesoriosArgentinos.Modelos.Marca", "Marca")
                        .WithMany("Piezas")
                        .HasForeignKey("MarcaId");

                    b.HasOne("AccesoriosArgentinos.Modelos.Material", "Material")
                        .WithMany("Piezas")
                        .HasForeignKey("MaterialId");

                    b.HasOne("AccesoriosArgentinos.Modelos.Matriz", "Matriz")
                        .WithMany("Piezas")
                        .HasForeignKey("MatrizId");

                    b.Navigation("Inyectora");

                    b.Navigation("Marca");

                    b.Navigation("Material");

                    b.Navigation("Matriz");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Deposito", b =>
                {
                    b.Navigation("Matrices");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.EstadosProduccion", b =>
                {
                    b.Navigation("OrdenesProduccionDetalles");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Inyectora", b =>
                {
                    b.Navigation("OrdenesProduccionCabeceras");

                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Marca", b =>
                {
                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Material", b =>
                {
                    b.Navigation("MaterialPiezas");

                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Matriz", b =>
                {
                    b.Navigation("OrdenesProduccionDetalles");

                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Operario", b =>
                {
                    b.Navigation("OrdenesProduccionDetalles");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.OrdenesProduccionCabecera", b =>
                {
                    b.Navigation("OrdenesProduccionDetalles");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Pieza", b =>
                {
                    b.Navigation("MaterialPiezas");

                    b.Navigation("OrdenesProduccionDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
