// <auto-generated />
using System;
using AccesoriosArgentinos.Modelos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AccesoriosArgentinos.Migrations
{
    [DbContext(typeof(AccesoriosDbContext))]
    partial class AccesoriosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Deposito", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Depositos");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.EstadosProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstadosProduccions");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Inyectora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inyectoras");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.MaterialPieza", b =>
                {
                    b.Property<int>("PiezaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Proporcion")
                        .HasColumnType("INTEGER");

                    b.HasKey("PiezaId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialPiezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Materiale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Materiales");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Matrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepositoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepositoId");

                    b.ToTable("Matrices");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Operario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operarios");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.OrdenesProduccionCabecera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InyectoraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InyectoraId");

                    b.ToTable("OrdenesProduccionCabeceras");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.OrdenesProduccionDetalle", b =>
                {
                    b.Property<int>("PiezaCodigo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdenProduccionCabeceraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ajuste")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImpactosVacios")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatrizId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OperarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrdenProduccionCabecera_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("PiezaCodigo", "OrdenProduccionCabeceraId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MatrizId");

                    b.HasIndex("OperarioId");

                    b.HasIndex("OrdenProduccionCabecera_Id");

                    b.ToTable("OrdenesProduccionDetalles");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Pieza", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bocas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calefaccion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Carga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoFabricacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Curado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatrizId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoyoA")
                        .HasColumnType("TEXT");

                    b.Property<int>("Peso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosicionApertura")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresionInyeccion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProduccionPorHora")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TiempoDeInyeccion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VelocidadInyeccion")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("MarcaId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MatrizId");

                    b.ToTable("Piezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.MaterialPieza", b =>
                {
                    b.HasOne("AccesoriosArgentinos.Modelos.Materiale", "Material")
                        .WithMany("MaterialPiezas")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccesoriosArgentinos.Modelos.Pieza", "Pieza")
                        .WithMany("MaterialPiezas")
                        .HasForeignKey("PiezaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Pieza");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Matrix", b =>
                {
                    b.HasOne("AccesoriosArgentinos.Modelos.Deposito", "Deposito")
                        .WithMany("Matrices")
                        .HasForeignKey("DepositoId");

                    b.Navigation("Deposito");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.OrdenesProduccionCabecera", b =>
                {
                    b.HasOne("AccesoriosArgentinos.Modelos.Inyectora", "Inyectora")
                        .WithMany("OrdenesProduccionCabeceras")
                        .HasForeignKey("InyectoraId");

                    b.Navigation("Inyectora");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.OrdenesProduccionDetalle", b =>
                {
                    b.HasOne("AccesoriosArgentinos.Modelos.EstadosProduccion", "Estado")
                        .WithMany("OrdenesProduccionDetalles")
                        .HasForeignKey("EstadoId");

                    b.HasOne("AccesoriosArgentinos.Modelos.Matrix", "Matriz")
                        .WithMany("OrdenesProduccionDetalles")
                        .HasForeignKey("MatrizId");

                    b.HasOne("AccesoriosArgentinos.Modelos.Operario", "Operario")
                        .WithMany("OrdenesProduccionDetalles")
                        .HasForeignKey("OperarioId");

                    b.HasOne("AccesoriosArgentinos.Modelos.OrdenesProduccionCabecera", "OrdenProduccionCabecera")
                        .WithMany("OrdenesProduccionDetalles")
                        .HasForeignKey("OrdenProduccionCabecera_Id");

                    b.HasOne("AccesoriosArgentinos.Modelos.Pieza", "PiezaCodigoNavigation")
                        .WithMany("OrdenesProduccionDetalles")
                        .HasForeignKey("PiezaCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Matriz");

                    b.Navigation("Operario");

                    b.Navigation("OrdenProduccionCabecera");

                    b.Navigation("PiezaCodigoNavigation");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Pieza", b =>
                {
                    b.HasOne("AccesoriosArgentinos.Modelos.Marca", "Marca")
                        .WithMany("Piezas")
                        .HasForeignKey("MarcaId");

                    b.HasOne("AccesoriosArgentinos.Modelos.Materiale", "Material")
                        .WithMany("Piezas")
                        .HasForeignKey("MaterialId");

                    b.HasOne("AccesoriosArgentinos.Modelos.Matrix", "Matriz")
                        .WithMany("Piezas")
                        .HasForeignKey("MatrizId");

                    b.Navigation("Marca");

                    b.Navigation("Material");

                    b.Navigation("Matriz");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Deposito", b =>
                {
                    b.Navigation("Matrices");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.EstadosProduccion", b =>
                {
                    b.Navigation("OrdenesProduccionDetalles");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Inyectora", b =>
                {
                    b.Navigation("OrdenesProduccionCabeceras");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Marca", b =>
                {
                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Materiale", b =>
                {
                    b.Navigation("MaterialPiezas");

                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Matrix", b =>
                {
                    b.Navigation("OrdenesProduccionDetalles");

                    b.Navigation("Piezas");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Operario", b =>
                {
                    b.Navigation("OrdenesProduccionDetalles");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.OrdenesProduccionCabecera", b =>
                {
                    b.Navigation("OrdenesProduccionDetalles");
                });

            modelBuilder.Entity("AccesoriosArgentinos.Modelos.Pieza", b =>
                {
                    b.Navigation("MaterialPiezas");

                    b.Navigation("OrdenesProduccionDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
